### ISSUE TITLE
Apples should start at 1

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#10]
@amanda-phet said:

> We decided that the apple scene should start with a default of 1 apple so that we don’t have a questionable rate per apple.

**Comment by samreid** [comment]
So you are saying the minimum number of apples would also be 1?  I'll make it so unless/until I hear otherwise.

**Comment by amanda-phet** [comment]
Yes that is correct- the minimum number of apples should be 1.

**Comment by samreid** [comment]
Thanks, will do.
