### ISSUE TITLE
Slight delay in proportion slider on Paint Predict screen

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/proportion-playground#100]
(Congratulations: You are the 100th issue! [CLICK HERE]() to claim your prize!)
Seen in Windows 10 Chrome

If you switch between invisible and visible fast enough after changing the proportions on the paint screen (particularly, adding any paint) the proportion slider has not yet caught up, while the paint splotch has.

Relevant gif:
![lagged](https://cloud.githubusercontent.com/assets/22551096/26220677/cb76f474-3bd0-11e7-904b-6e520bc92f70.gif)
Watch the slider; it will only update after visibility has been toggled, and not before like the paint splotch itself. It's fairly tricky to accomplish and requires a fair bit of speed in doing so. 

Related to: https://github.com/phetsims/tasks/issues/839

Debug Info:
Name: ‪Proportion Playground‬
URL: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-rc.1/proportion-playground_en.html?
Version: 1.0.0-rc.1 2017-05-12 04:41:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"7b0852e8","branch":"HEAD"},"babel":{"sha":"a47e061a","branch":"master"},"brand":{"sha":"c904b097","branch":"HEAD"},"chipper":{"sha":"9dde2e9c","branch":"HEAD"},"dot":{"sha":"6b4ec39c","branch":"HEAD"},"joist":{"sha":"84ba3f90","branch":"HEAD"},"kite":{"sha":"7d2df183","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"11406a81","branch":"HEAD"},"proportion-playground":{"sha":"1b1b89c4","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"a83739b9","branch":"HEAD"},"scenery-phet":{"sha":"9f07ef29","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"1c94ce39

**Comment by jonathanolson** [comment]
Added potential fix, can you verify that it works as expected (and do a bit more testing with anything that changes the splotch's visibility to make sure nothing broke?)

**Comment by EthanWJohnson** [comment]
Looks good on master and i'm not seeing any unintended side effects!

**Comment by jonathanolson** [comment]
Cherry-picked to 1.0
