### ISSUE TITLE
Screenshot needed

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#102]
@phet-steele can you please take a screenshot for publication using the iPad? 

If you have thoughts about a good screenshot please chime in, but I figure this one will work well. If you wanted to snap the screenshot while the ball is still in motion (after 3 bounces maybe) that works too!

<img width="917" alt="screen shot 2017-05-31 at 8 40 24 am" src="https://cloud.githubusercontent.com/assets/7852916/26637633/356f3d62-45dd-11e7-8945-b61fbda7d098.png">

**Comment by phet-steele** [comment]
@amanda-phet please look at the screenshot in the above commit. If all is well, assign to @jonathanolson to cherry-pick the commit to 1.0

**Comment by ariel-phet** [comment]
@phet-steele as per our new policy, please take a few additional screenshots so I can use them on Edmodo and such.

**Comment by phet-steele** [comment]
> @phet-steele as per our new policy, please take a few additional screenshots so I can use them on Edmodo and such.

I already have, just waiting on the approval of this one. Don't worry man I got it handled!

**Comment by amanda-phet** [comment]
Looks good to me. Thank you! 

Assigning to @jonathanolson to add this to 1.0.0. Once I have confirmation that the screenshot is good to go I can make the sim visible.

**Comment by jonathanolson** [comment]
I manually added the screenshot to the 1.0 branch, generated the thumbnails and twitter card, and got the OK from @mattpen that its structure looks fine on phet-server.

@amanda-phet, feel free to make it visible whenever you are ready.

**Comment by amanda-phet** [comment]
Done!
