### ISSUE TITLE
Increase ball speed for larger tables?

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#13]
@ariel-phet suggested:

> You might want to implement an algorithm whereby the speed of the ball increases with increased table size (not getting too fast, but at a large table size the pattern can take a very long time to draw, which generally breaks our rule of having students "watch" an animation).

**Comment by samreid** [comment]
I'd be interested to see what the current situation sounds like with sound effects, then to experiment increased ball speed and see what that sounds like.  Generally I agree with not having students watch an animation, but I'm not sure if the audio pattern will want to keep the same "beat".

**Comment by amanda-phet** [comment]
As I think about the potential sound effects, I wonder what they will do for helping a student understand this representation better. We want students to notice the white pattern on the table, and the sound might accentuate the number of bounces more than the pattern. However, some tables, like 1xn or nxn, have a distinctive pattern that could be more pronounced with sound. Tables like 3x4 and 6x8 will have the same pattern (and we want students to notice that!), so if a faster speed would make the sounds identical, which I think would help a lot with the learning goals!

**Comment by amanda-phet** [comment]
Discussed in 12/8 meeting and @jonathanolson will play around with the speed so that bigger tables move slightly faster than smaller tables.

**Comment by jonathanolson** [comment]
Implemented my best attempt so far at http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.16/proportion-playground_en.html.

If that doesn't look good (or could use some tweaks), this dev release also features a fun (very temporary) query parameter 'billiardSpeed', that allows you to type in your own formula with the following:

- distance (amount of distance covered by the ball)
- bumps (number of walls it bumps into, including the end corner)
- gcd (the greatest common divisor of the length and width)
- a (the length)
- b (the width)
- Mathematical operators, such as Math.pow( base, exponent ), Math.sqrt( n ), parenthesis, binary operations (```+-*/```), spaces, and digits.

In Chrome, you can write ```?billiardSpeed=``` and then put in the formula. For example, the current default (```http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.16/proportion-playground_en.html?billiardSpeed=8 * Math.sqrt( distance ) / Math.sqrt( bumps )```), and Chrome will automatically encode it.

**Comment by amanda-phet** [comment]
With the current version, I compared 20x19 and 5x6 and 5x6 seemed too fast. I will play with the query parameter tonight.

**Comment by amanda-phet** [comment]
I'm trying to calculate a query parameter to reflect what we discussed in our last meeting, which was to have the speed for both tables be such that both tables take the same amount of time to cross the table to the first bounce. This means I'd need variables for the length and width of *both* tables. So instead I'm just trying to come up with one speed for the diagonal length and will test it on differently sized tables. 

So, I am am trying to figure out how to use ```?billiardSpeed=``` and decided to start with this to get a baseline:  
``` ?billiardSpeed=Math.sqrt(Math.pow(a,2)+Math.pow(b,2))```

However the sim won't load, so I must be doing something wrong. @jonathanolson can you help me out here?

**Comment by jonathanolson** [comment]
Looks like I forgot to allow commas (like the ones in Math.pow). I'll enable that and a few more "Math.*" expressions like "min", "max" and "abs".

**Comment by jonathanolson** [comment]
Applied fixes in master, your query parameter should now work.

**Comment by amanda-phet** [comment]
http://phettest.colorado.edu/proportion-playground/proportion-playground_en.html?billiardSpeed=3/2*Math.sqrt(Math.pow(a,2)+Math.pow(b,2)) looks like the winner to me! 

Similar tables will end at the same time (compare 5:4 and 10:8 using this parameter and dev.16!), paths with many bounces go very fast, and paths with no bounces don't go super slow (except 1x1, and it feels appropriate to me). 

@kathy-phet and @ariel-phet please take a look at it and see what you think.

**Comment by kathy-phet** [comment]
+1 Looks good to me.

**Comment by amanda-phet** [comment]
Looks good to everyone!

**Comment by jonathanolson** [comment]
Made that the default, and removed the temporary query parameter.

Anything else to do here?

**Comment by amanda-phet** [comment]
Nope. Thank you!
