### ISSUE TITLE
What is the source of this paint bucket image?

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#15]
I pulled this paint bucket image from the design doc:

![image](https://cloud.githubusercontent.com/assets/679486/15563470/14b4979c-22c6-11e6-90e9-ccdb805b769d.png)

Was it created by our artist or does it have a license encumbrance?

**Comment by ariel-phet** [comment]
This is a question for @amanda-phet as I am not sure of the answer

**Comment by amanda-phet** [comment]
I created it based on a Google image. It is a placeholder image, though. I think Mariah made a different image that we will use.

Get Outlook for Androidhttps://aka.ms/ghei36

On Wed, May 25, 2016 at 10:04 PM -0700, "Ariel Paul" <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #15https://github.com/phetsims/proportion-playground/issues/15 to @amanda-phethttps://github.com/amanda-phet.

##

**Comment by amanda-phet** [comment]
I'd like to replace this image with paint balloons, since there are no other instances of paint buckets in the scene.
![paint-scene-01](https://cloud.githubusercontent.com/assets/7852916/22118029/6d7dd8ec-de33-11e6-804f-76d7f792df51.png)

**Comment by jonathanolson** [comment]
Done.

**Comment by amanda-phet** [comment]
The image looks pretty terrible in Firefox. Should I export a higher-res image? Or do we pick our battles and stop fighting with Firefox when it comes to images?

**Comment by samreid** [comment]
Here's how it looks in my Firefox on retina (it actually looks a bit better because it is 1/2 this size).  What does it look like on your firefox?  
![image](https://cloud.githubusercontent.com/assets/679486/22156615/4e460468-def1-11e6-8b13-1060a08e8042.png)

> Should I export a higher-res image?

Sometimes the solution is to provide a *smaller* image so that firefox doesn't have to scale it so much.  But let's look at your screenshot first to see the exact problem.

**Comment by amanda-phet** [comment]
![screen shot 2017-01-20 at 9 20 39 am](https://cloud.githubusercontent.com/assets/7852916/22156706/c084f14c-def1-11e6-899a-e31d288ed929.png)

**Comment by samreid** [comment]
That is pretty bad, what is your OS and Firefox version?

**Comment by amanda-phet** [comment]
OSX 10.11.6
Firefox 50.0.2

So, not totally up-to-date.

**Comment by samreid** [comment]
Is your display retina or non-retina?

**Comment by amanda-phet** [comment]
It's a high-res external monitor. 

Here is my retina display:
<img width="307" alt="screen shot 2017-01-20 at 9 34 13 am" src="https://cloud.githubusercontent.com/assets/7852916/22157138/aa29fc1a-def3-11e6-96ee-54689767e79f.png">
It seems much better here.

**Comment by jonathanolson** [comment]
I accidentally used "image" instead of "mipmap", I'll fix it.

**Comment by jonathanolson** [comment]
It's mipmapped now.

**Comment by amanda-phet** [comment]
Looks much better on my monitor!
