### ISSUE TITLE
Screen icons are needed

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#18]
Currently the homescreen and navbar icons are solid rectangles.

**Comment by amanda-phet** [comment]
<img width="681" alt="screen shot 2017-01-26 at 2 03 29 pm" src="https://cloud.githubusercontent.com/assets/7852916/22350251/52fe8e92-e3d0-11e6-8986-20c6f1eeeaf0.png">

Navbar icons should look like this: 
<img width="192" alt="screen shot 2017-01-26 at 2 04 46 pm" src="https://cloud.githubusercontent.com/assets/7852916/22350293/71bc501c-e3d0-11e6-9f38-9af735c952db.png">

**Comment by jonathanolson** [comment]
So the predict nav-bar icon should NOT have a colon?

**Comment by amanda-phet** [comment]
We should see how it looks, but that is correct. I think reducing clutter in the smaller icon might be helpful.

**Comment by amanda-phet** [comment]
Now that I looks at it, actually, I think the paint splotch should be lighter. Can you make it orange instead?
![screen shot 2017-01-27 at 11 36 20 am](https://cloud.githubusercontent.com/assets/7852916/22382908/de7e97dc-e484-11e6-97f3-8a4f85c9a25c.png)

**Comment by jonathanolson** [comment]
Should I presume that none of those labels should be translatable?

**Comment by amanda-phet** [comment]
Do you mean the 6:3 and ?:? text? That's probably fine to make them not translatable, but I'm not sure how other countries write ratios.

**Comment by amanda-phet** [comment]
Not sure how to describe this bug, but the billiard ball seems to have fallen off the table... 
![screen shot 2017-01-30 at 3 52 16 pm](https://cloud.githubusercontent.com/assets/7852916/22445332/2d87716a-e704-11e6-8670-e7d3c33e9e0f.png)

**Comment by jonathanolson** [comment]
I haven't cleaned up the billiards display code yet, and it is buggy when you give it certain billiards states. I'll have that fixed soon (it's why I'm still assigned to this issue, otherwise the icons are ready).

**Comment by jonathanolson** [comment]
That bug should be fixed now.

**Comment by amanda-phet** [comment]
Looks great now!
