### ISSUE TITLE
offset / redraw issue where the table gets off center

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#19]
@kathy-phet said:

> Small bug on the pool table scene -- when decreasing the vertical or horizontal size (after making it larger) there is an offset / redraw issue where the table gets off center. It fixes itself if you continue to get smaller. 

![image](https://cloud.githubusercontent.com/assets/679486/15655881/ae00547c-265e-11e6-8ad6-001fce963976.png)

**Comment by samreid** [comment]
Fixed above, on hold until published for testing.

**Comment by samreid** [comment]
Published in http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.12/proportion-playground_en.html

I'll email @kathy-phet to review.

**Comment by jonathanolson** [comment]
I haven't seen this, closing.
