### ISSUE TITLE
AI files needed

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#2]
@ariel-phet said he would contact @mariahmaephet to request the artwork.

**Comment by samreid** [comment]
Note: some of the artwork is here in tasks: https://github.com/phetsims/tasks/issues/468

**Comment by ariel-phet** [comment]
@samreid the .ai files have been uploaded to drive

https://drive.google.com/drive/folders/0B-YvjkIIcS_aRVFvZ2NDYlZ6Qkk

There are several files

balloons.ai
beads.ai
crate.ai
fruitstand.ai
fruitstand2.ai
objects.ai

**Comment by samreid** [comment]
I added the aforementioned AI files in the above commit and will close this issue. @ariel-phet and @mariahmaephet please let me know if there is new artwork.
