### ISSUE TITLE
Write the price tags as "per apple"

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#21]
@kathy-phet said:

And write the $0.50 as $0.50/1 apple --- with a horizontal divider line. As it is written in unit rates. 

--- Note --none of these are critical for Wed.  But they would be valued if available.

**Comment by samreid** [comment]
Perhaps this is how it looks in unit rates:

![image](https://cloud.githubusercontent.com/assets/679486/15657337/2678ee74-266d-11e6-8dfd-4a9d95937428.png)

**Comment by samreid** [comment]
New price tag is looking like this:

![image](https://cloud.githubusercontent.com/assets/679486/15657446/0fa0068c-266e-11e6-8a68-013d7f568356.png)

**Comment by samreid** [comment]
Published in http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.12/proportion-playground_en.html

I'll email @kathy-phet to review.

**Comment by amanda-phet** [comment]
I think this looks really good.

**Comment by samreid** [comment]
Thanks @amanda-phet, I'll close the issue.
