### ISSUE TITLE
Make indicators on Apples scene graph the same distance

### ISSUE THREAD

**Issue by andrealin** [phetsims/proportion-playground#25]
@phet-steele noticed that in Apple scene, the right indicator triangle is further away from the line than the left indicator triangle:
![image](https://cloud.githubusercontent.com/assets/7988696/15982043/d7263778-2f3b-11e6-868e-6e1787f61763.png)

**Comment by andrealin** [comment]
Fixed in commit https://github.com/phetsims/proportion-playground/commit/1e081493e1a34f3a71ec5c7ab2dc4f0249f359d2 by changing the right and left boundaries of the indicator triangles:

``` js
var leftIndicator = new TriangleNode( 'left', { right: - arrowWidth / 2 } );
var rightIndicator = new TriangleNode( 'right', { left: arrowWidth / 2 } );
```

(original:

``` js
var leftIndicator = new TriangleNode( 'left', { right: 0 } );
var rightIndicator = new TriangleNode( 'right', { left: arrowWidth } );
```

)

It now looks even:
![image](https://cloud.githubusercontent.com/assets/7988696/15982073/5e2f060a-2f3c-11e6-8551-a65770f1a5e7.png)

@ariel-phet @samreid Is this a good thing to document in an issue? Or would I normally comment this on the commit itself?

**Comment by samreid** [comment]
> Is this a good thing to document in an issue?

Yes, creating an issue for things like this has many advantages from a project management and maintenance side.  The main exception to this rule is when a new simulation or project is being started--in that case, many commits may be made before the first issues are created.

**Comment by samreid** [comment]
The code change and new screen shot depicted above look great, you may close the issue if there is nothing else to do here.

**Comment by andrealin** [comment]
Sounds good. Closing.
