### ISSUE TITLE
Dragging a side to change the dimensions of the table

### ISSUE THREAD

**Issue by andrealin** [phetsims/proportion-playground#26]
@ariel-phet told me that it's been discussed it would be nice if one could drag a corner of the billiard table to change the dimensions. Self assigning.

**Comment by amanda-phet** [comment]
I believe the discussion was to drag a side of the table, not a corner. It has a bit more impact to see just one dimension change at a time. 

A design issue with this is that the table is centered around a specific point, so as the table resizes it will also jump around to re-center. 

I'm happy to skype with you about this to brainstorm how it could look and function!

**Comment by andrealin** [comment]
That would make sense. Perhaps side and corner? Let me get acquainted with the code to see what I can manage to do, and then we can skype.

**Comment by andrealin** [comment]
@amanda-phet would you have time to skype some time next week?

**Comment by andrealin** [comment]
@amanda-phet the basic functionality is all set. Assigning back to you for design decisions, such as a handle for a visual cue. Will expand the mouse and finger touch areas when visual cue has been decided on.

**Comment by amanda-phet** [comment]
This functionality is in place and working well, and since a new issue is now open regarding the design I will close this issue.
