### ISSUE TITLE
Color of spinners

### ISSUE THREAD

**Issue by andrealin** [phetsims/proportion-playground#27]
@amanda-phet noticed that all the spinners are blue, except for on the paint scene. Perhaps, use black or color code based on what they are controlling.

**Comment by andrealin** [comment]
Today's meeting notes about this, also on the design doc:

> AL will change the bead spinners to be color-coded, try brown or green for billiards and make a decision about what looks best, and red for apple spinner + black for cost spinner. AL will make a github issue.

**Comment by andrealin** [comment]
@amanda-phet take a look on [phettest](http://phettest.colorado.edu/proportion-playground/proportion-playground_en.html?ea&brand=phet), and feel free to close.

**Comment by amanda-phet** [comment]
Looks great.
