### ISSUE TITLE
 Toggles are jumping between scenes

### ISSUE THREAD

**Issue by andrealin** [phetsims/proportion-playground#28]
@amanda-phet noticed (see meeting notes in design doc)

> the toggles at the bottom of the screen (to go from single to double view) are jumping around in location from scene to scene. It would be nice for these to remain in a fixed location since they are a constant control on all scenes/screens.

**Comment by andrealin** [comment]
@amanda-phet Here is the latest dev version: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.14/proportion-playground_en.html Could you take a look when you have time?

**Comment by amanda-phet** [comment]
Beautiful! 

If we change the artwork next to the toggles, will this need to be tweaked again? Or should it be able to handle new artwork? (Not saying this will happen, but you never know!)

**Comment by andrealin** [comment]
@amanda-phet This implementation should be able to handle new artwork. The artwork would become scaled when it is created as an icon, and as long as that icon next to the toggles is not much bigger in height than the toggle (1.6 times bigger, to be exact ), the toggles will not move. Thanks for mentioning this, I will also add documentation in the code to explain this.

**Comment by amanda-phet** [comment]
Great! I'll go ahead and close this issue then.
