### ISSUE TITLE
Review current state of the sim

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/proportion-playground#31]
@jonathanolson as discussed, it would be good to review the current state of the code in the sim and get a feel for how much work will need to be done to bring it up to code standards and such.

It would be good to do this initial review the week of 11/28/2016 after meeting with @amanda-phet to make sure you are clear on the learning goals and flow of the sim.

**Comment by jonathanolson** [comment]
Current state is pretty good, still have some view code to review/clean up (particularly with the necklace).

**Comment by ariel-phet** [comment]
Since @jonathanolson has been working on this sim as the main developer, I think we can consider initial review complete
