### ISSUE TITLE
Tweak button behavior on Predict screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#32]
1. When opening the Predict screen, the "show/hide" button should appear disabled until the user interacts with a spinner. After a spinner is touched, the button appears to be enabled.

2. The current implementation is going for a "depressed" look when pressed. Instead, we'd like to use the same appearance as the Function Builder Mystery screen, where the button toggles between an open eye and an eye with a slash. 

@jonathanolson let me know if you need artwork for the eye, or if you can get it from Function Builder. The icon might even be fontawesome, but I'm not sure. 

3. The location of the button should be centered above the toggle for all four scenes (currently in an odd location on Billiards scene).

**Comment by jonathanolson** [comment]
(1) and (2) are done. Wasn't sure about whether it is scene-specific or screen-specific (currently handling it for each scene), or what reset-all should do (resets it to disabled), let me know about changes.

> The location of the button should be centered above the toggle for all four scenes (currently in an odd location on Billiards scene).

Not really sure what location you mean, is it one of the following (black circles):
![screen shot 2016-12-09 at 6 10 24 pm](https://cloud.githubusercontent.com/assets/480878/21069893/ab4b5a7c-be3b-11e6-9c55-7e5c9aba62cd.png)
I recall some discussion about having it "between" the spinners, but that would be different in the Apple case, but I don't recall any decision.

**Comment by amanda-phet** [comment]
For (3) I meant to continue the work you were doing to put the button in a reasonable location. In the Billiards scene, when two tables are displayed, the button would be centered at the bottom of the screen above the toggle. I see now that it can't be in the exact same location as the other scenes, due to the size of the table, but where it is now still seems better than off to the left side. 

The button looks good to me in all the scenes!
