### ISSUE TITLE
Add animation to paint scene

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#33]
When the user clicks a spinner on the paint scene, a "ball" of paint should fly toward the paint splotch to indicate why it is growing in size.

**Comment by jonathanolson** [comment]
Implemented on a branch, see http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.15-paintballoons/proportion-playground_en.html for testing.

I chose to only update the splotch/arrows when the "balloon" actually hits. Removing paint removes it immediately (throwing something to soak paint didn't sound helpful), but it seems a bit weird.

Personally, it feels more playful (especially when holding down a spinner to loose a volley), but also more confusing (with immediate paint removal, other options?) and slower to interact with (extra time spent waiting for the "balloons" to land, to see how the splotch updates. Might add complexity to a game screen, where you need to wait for balloons to land before comparing answers.

**Comment by amanda-phet** [comment]
I don't mind the extra wait time while the ball flies.. this is looking great. 

For the removal, could a ball of paint sort of "drip" off, and just fall vertically off the screen? I don't terribly mind the removal as it is if we can't think of something.

**Comment by jonathanolson** [comment]
@ariel-phet was mentioning that paint balloons could fly off in the reverse direction when paint is removed, and that would be easy to animate. Any thoughts on that?

**Comment by amanda-phet** [comment]
If I add paint and then remove before the balloons have finished flying, there could be a strange overlap. If it's easy to implement we can see how it looks, but I'm thinking the two paths shouldn't overlap. 

If it's easy, let's try it, but keep in mind an alternate path, such as straight down.

**Comment by jonathanolson** [comment]
The more I thought about it, the better the "paint drip" sounded better. An initial prototype is implemented, let me know how it looks.

Also, I've implemented consistent paint-area preservation, so:

- Splotch area is now correct (it was actually something like ```displayedArea = actualArea^2 + maxArea / 2pi```, and is now fully proportional). That means there's now a bigger difference between 1 and 2, which is (unfortunately) noticeable in the "show both" switch at the bottom. I can normalize these so they will be the same.
- Both the balloon (at the size when it lands) and the drips (they maintain constant area through their distortion) have an area that matches a single splotch area. I was lazy, and used monte-carlo sampling to figure out the splotch shape area to match this (kite currently can't calculate this precisely).

**Comment by jonathanolson** [comment]
Pushed a change just now to make the blue and green "switch labels" the same size, so that shouldn't be an issue.

Feedback on the appearance?

Additionally, I'm planning on balloon graphics; I presume these need to be turned into 5 images based on the new colors?

**Comment by jonathanolson** [comment]
Also, I'd recommend a visual change to the behavior when you quickly increment and decrement the spinner:

Currently, it throws a balloon and can start the "drip" before the balloon has arrived.

I'd propose that it should wait for the balloon to "hit" before generating a drip (instantaneously, so there is no splotch size increase).

**Comment by jonathanolson** [comment]
Also, once we have balloon graphics, I'll add a random slight angular velocity to each balloon.

**Comment by jonathanolson** [comment]
Another note: for the bucket/balloon graphics, if you provide a "background" image without any paint, and a "paint" image of the same dimensions (with the paint being white or gray), I could create composite colorized images in code (color-multiply the "paint" image by our paint color, and composite that on top of the background).

That could prevent us from having to hand-create images if we slightly change the paint colors.

**Comment by ariel-phet** [comment]
Generally like the direction this is going, will leave it up to @amanda-phet and her artistic choices

**Comment by amanda-phet** [comment]
>Also, I'd recommend a visual change to the behavior when you quickly increment and decrement the spinner:
Currently, it throws a balloon and can start the "drip" before the balloon has arrived.
I'd propose that it should wait for the balloon to "hit" before generating a drip (instantaneously, so there is no splotch size increase).

This is a good suggestion. Let's go ahead an implement that change. 

This issue is still open as we work to implement 
1. the animation of the balloons flying at the paint splotch (artwork emailed to JO) 
2. the paint drip animation, based on email and discussion between AM and JO

**Comment by jonathanolson** [comment]
Added an initial drip animation. Thoughts on whether it is sufficient, or what improvements could be made?

**Comment by amanda-phet** [comment]
It's looking great to me! @ariel-phet and @kathy-phet can comment but I wouldn't change anything at the moment. 

The white drip can be a little hard to see on the light background. Would a black stroke look strange?

**Comment by jonathanolson** [comment]
> The white drip can be a little hard to see on the light background.

Also noticed this with the yellow. I'll try adding a little stroke.

**Comment by jonathanolson** [comment]
Looks nicer to me with the stroke.

Different background color may help 'white' or 'yellow' pop more (see http://phettest.colorado.edu/proportion-playground/proportion-playground-colors.html to try changing the background color or a few other things).

**Comment by ariel-phet** [comment]
I think the drip is looking quite nice!

**Comment by amanda-phet** [comment]
I like the stroke quite a bit! 

I was thinking we'd only change the background color on the predict screen, which doesn't show the paint drip, so I will close this issue.
