### ISSUE TITLE
Make the beads look realistic

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#34]
The beads on the necklace scene should have a more "3-D" feel. The round beads can be simply handled with the usual light source from the top-right (similar to how molecules look). The square beads will need something more in the code, since they rotate around the necklace. @jonathanolson will work on a programmatic approach for this that does not require drawing a gradient for every instance of the bead, but still gives some bevel and 3-D feel. 

A rough idea of the look and feel (but the square beads here are problematic): 
![screen shot 2016-12-09 at 10 51 31 am](https://cloud.githubusercontent.com/assets/7852916/21058942/7fea50c4-bdfd-11e6-9bea-6772fe858e60.png)

**Comment by jonathanolson** [comment]
Made an initial attempt, with some color changes to more closely match the colors displayed in the mock-up above:

![prop-bead-attempt-1](https://cloud.githubusercontent.com/assets/480878/21125753/1db975f6-c0a5-11e6-8c4e-ca2e730c0dac.PNG)

If we notice any performance issues with gradients, we can handle it then.

Thoughts on the appearance?

**Comment by amanda-phet** [comment]
The appearance looks great to me!
