### ISSUE TITLE
Add radio buttons to paint scene

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#35]
There should be three radio buttons on the paint scene, each with a representative gradient for the color choices. THe default selection is blue-yellow. With the addition of these ratio buttons, the "Black & White" checkbox should be removed. 

![screen shot 2016-12-09 at 10 53 15 am](https://cloud.githubusercontent.com/assets/7852916/21058996/bc07b1d2-bdfd-11e6-9eb1-dbeaa467ffba.png)

**Comment by jonathanolson** [comment]
Implemented.

Also I'd like to note I've reworked the code for generating the color values to one that should be much closer to physically accurate (using the weighted geometric mean to approximate subtractive color from experimental evidence with watercolor paint, http://www.handprint.com/HP/WCL/color3.html#mixprofile and http://scottburns.us/subtractive-color-mixture/, and then applying gamma correction).

I wasn't sure how much tweaking of exact colors had been done, but I can definitely adjust the current method to suit preferences (or if necessary, revert to the older method). I just have a preference for starting from something more accurate.

Let me know how it looks.

**Comment by jonathanolson** [comment]
Also, the current paint colors in hexadecimal RGB are:
```js
  var BLUE = new Color( 0x05, 0x70, 0xFF );
  var YELLOW = new Color( 0xFF, 0xE0, 0x05 );
  var RED = new Color( 0xFF, 0x25, 0x05 );
  var BLACK = new Color( 0x25, 0x25, 0x25 );
  var WHITE = new Color( 0xFF, 0xFF, 0xFF );
```
in case it doesn't need tweaks (and the colors need to be hard-coded into the bucket images).

I can also set up a color profile editor that will allow anyone to test different colors if desired (in the same style as http://phettest.colorado.edu/molecule-shapes/molecule-shapes-colors.html).

**Comment by amanda-phet** [comment]
Thank you- I will need those colors soon. 

The colors are looking great to me. Thank you for making them look more like mixing paint!
