### ISSUE TITLE
Small tweaks 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#36]
1. The triangle on the paint scene gradient should have no fill (it is currently white), could be slightly smaller, and could be more isosceles than equilateral. 

![screen shot 2016-12-12 at 3 47 23 pm](https://cloud.githubusercontent.com/assets/7852916/21120014/76939198-c082-11e6-82dc-ef77ca08b94e.png)

2. The triangle on the apple scene cost meter should match what we decide on in the paint scene. 
3. The apple scene cost meter should have a label above it that says "Apple cost".

**Comment by jonathanolson** [comment]
Done.

Added a fill (same as the background) on the arrow in the apple scene to prevent the following appearance:
![prop-no-fill](https://cloud.githubusercontent.com/assets/480878/21123640/1dfb3a12-c097-11e6-95f8-43a71e0226dc.PNG)
as I presume that isn't desired (let me know if it should look like that).

Also, there's somewhat a mix of capitalization, with "Total Cost", "Apple cost", "Cost per apple", "length" and "width". Is this by design, or can it be improved?

**Comment by amanda-phet** [comment]
>Added a fill (same as the background) on the arrow in the apple scene 

Looks great. We may need something similar on the paint scene.. or is there room to just add more space between the paint splotch and the gradient? 
![screen shot 2016-12-13 at 10 35 55 am](https://cloud.githubusercontent.com/assets/7852916/21151498/f71025c8-c11f-11e6-9fdd-fd6131a26dee.png)

>Also, there's somewhat a mix of capitalization, with "Total Cost", "Apple cost", "Cost per apple", "length" and "width". Is this by design, or can it be improved? 

That is not by design, and should be improved. We generally do "title case", right? So that means we should change 
* Cost per apple --> Cost per Apple
* Apple cost --> Apple Cost 

Does that seem consistent?

**Comment by jonathanolson** [comment]
Pushed the splotches slightly further away to avoid overlap, and fixed title casing (as length=>Length, width=>Width).

Do those changes look good?

**Comment by amanda-phet** [comment]
I'm not seeing the title casing changes on phettest, but the spacing of the paint splotches looks great.

**Comment by jonathanolson** [comment]
Could be a caching issue? Changes show for me. Try clearing caches, or an incognito tab?

**Comment by amanda-phet** [comment]
All looks good to me. Thanks!
