### ISSUE TITLE
Add pattern readout to Bead scene

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#37]
As discussed in the 12/8/16 design meeting, we want to add a representation to help students interpret the ratios in the Bead scene. The pattern should be simple, abstracted beads (flat, no gradient) that start just under the word Pattern. This strand should be the simplified ratio of beads. The screenshot below shows en example for two different necklaces. 

The height of the box needs to be able to contain a strand of 39 beads. The box should have a white fill and light gray (currently using #B3B3B3) stroke. Let's see if we like the square corners before rounding them.

I'm not sure of the best way to handle translations to the word Pattern. Can you determine a max width for the bounding box to resize, and after that point the word can shrink in size? 

![screen shot 2016-12-13 at 12 16 38 pm](https://cloud.githubusercontent.com/assets/7852916/21155114/0c6e7d1c-c12e-11e6-9733-9672d731103a.png)

![screen shot 2016-12-13 at 12 16 47 pm](https://cloud.githubusercontent.com/assets/7852916/21155118/0f6e7ddc-c12e-11e6-86d9-19a5c82810d1.png)

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

I also had to move the reveal button, since it was right under the pattern panel:
![prop-reveal-necklace](https://cloud.githubusercontent.com/assets/480878/21172177/9e2b58ce-c18d-11e6-8eca-2be4d0ce91a6.PNG)

If there's a better location for that situation, let me know!

**Comment by amanda-phet** [comment]
I sort of anticipated the button needing a new placement but wanted to wait and see how much space the pattern readout took up. 

The screenshot looks good to me. 

I'm having trouble (again) viewing the latest version, and am in a private browsing window on VPN, so I'll try again tomorrow when I'm on campus.

**Comment by amanda-phet** [comment]
This looks good to me, as long as #39 gets addressed. 

I anticipated that we might need to move the reveal button, but wanted to see if there was room to shrink the Pattern readout. Right now I think the button location is fine and can see in the next round of interviews if the location is problematic between scenes.

**Comment by amanda-phet** [comment]
One minor change: round the corners a tiny bit.

**Comment by jonathanolson** [comment]
Rounded corners in master, let me know if other changes are required (like reversing the pattern like we reversed the beads).

**Comment by amanda-phet** [comment]
Looks nice. Thanks.
