### ISSUE TITLE
Reverse direction of beads

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#39]
I'm not sure how I didn't notice this before, but the bead pattern should start with red and go *counter-clockwise* around the necklace. 

Currently seems to go clockwise: 
![screen shot 2016-12-14 at 11 39 12 am](https://cloud.githubusercontent.com/assets/7852916/21195670/f999ded8-c1f1-11e6-810c-ce14a99462eb.png)

But should look more like this (ignoring the out-dated appearance of beads): 
![screen shot 2016-12-14 at 11 38 53 am](https://cloud.githubusercontent.com/assets/7852916/21195696/0f27f712-c1f2-11e6-9d12-ca7fa3a529ab.png)

**Comment by jonathanolson** [comment]
Done.

Did you want the pattern display reversed also?

**Comment by amanda-phet** [comment]
No, the necklace matches the pattern display with this change. Thanks!
