### ISSUE TITLE
Move toggle up a bit from the navbar

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#40]
The toggle is a little too close to the navbar right now. If possible, it would be good to nudge it up a little bit.

**Comment by amanda-phet** [comment]
Related: on the billiards scene, to account for this move and ideally moving the reveal button up, see if there is room to shift the tables up closer to the scene selection buttons.

**Comment by jonathanolson** [comment]
Made the described improvements and fixed a few alignment issues. Can you take a look?

**Comment by amanda-phet** [comment]
Looks great.
