### ISSUE TITLE
Add paint balloons to paint scene

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#42]
Emailing @jonathanolson assets now. These are the paint balloons that will be thrown at the paint splotch on the Explore screen. 

Happy to make changes to the appearance if people have suggestions!
<img width="610" alt="screen shot 2016-12-22 at 11 30 24 am" src="https://cloud.githubusercontent.com/assets/7852916/21436117/25cc4ede-c83a-11e6-8b5b-8d454f50e278.png">

**Comment by amanda-phet** [comment]
In the 1/12/17 design meeting we decided that there should be a few different orientations for balloons and one will randomly be selected to throw at the paint splotch. Here are three variations: 

![screen shot 2017-01-16 at 3 00 06 pm](https://cloud.githubusercontent.com/assets/7852916/22000488/98255838-dbfc-11e6-8b46-e3f9ebe28db5.png)

**Comment by amanda-phet** [comment]
emailed exported images to @jonathanolson

**Comment by jonathanolson** [comment]
Initial implementation, let me know how it looks. May be able to increase the size of the balloons, depending on the new splotch graphic (not yet done).

**Comment by amanda-phet** [comment]
They look so CUTE! 

I just realized that the light is coming from the wrong angle (we usually do top-right and these are top-left), so I should probably update the images.

**Comment by ariel-phet** [comment]
@amanda-phet I believe top-left is our usual standard for lighting actually

**Comment by ariel-phet** [comment]
Notice for instance probe head in bending light, or the alpha particle generator in Rutherford scattering

**Comment by amanda-phet** [comment]
@ariel-phet thanks. That means I should update the apples, then!

**Comment by amanda-phet** [comment]
The beads also have the light source coming from top-right, so we'll need to adjust that as well. I'll make a separate issue.

**Comment by amanda-phet** [comment]
Balloons look great, and other issues have been opened. Closing this one.
