### ISSUE TITLE
Add grippy dots to sides of billiards table

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#43]
Mockup of new thicker, black border, and three grippy dots. 

The left board shows the *smallest* possible board, so the dots must fit within that space. The left board also has dots on only two sides. 

The right board shows the *largest* possible board, and has dots on all four sides. 

Specifics worth discussing: 
1. size and spacing of dots
2. color of dots
3. if we want dots on two sides or on all four sides

![screen shot 2017-01-05 at 3 48 12 pm](https://cloud.githubusercontent.com/assets/7852916/21700613/82c13ae4-d35e-11e6-92bd-03a55873d692.png)

**Comment by ariel-phet** [comment]
@amanda-phet I think the dots size/spacing/color look good, these seem to follow the idea of the "minimum effective difference" -- you can discern them, but they are not obtrusive.

I think we all agree that is not critical that a user finds this feature, so something subtle seems to work well. Certainly I think the cursor should change to the double headed expansion arrow cursor when hovering these spots.

I think I would put the dots on all four sides...it just seems more natural and symmetric when I see it in a mockup.

It also appears the the right hand board has slightly smaller corner pockets that fit better in the space of the black border, that seems preferable.

**Comment by amanda-phet** [comment]
Thank you for your feedback @ariel-phet ! The small table actually had a border that was smaller, so I matched it to the larger one and put the dots on all four sides. 

The cursor already does change to a hand when hovered over the resizing region, but we could make it something like ew-resize and ns-resize that you see here: http://phetsims.github.io/scenery/examples/cursors.html 

Updated mockup: 
![screen shot 2017-01-06 at 12 07 04 pm](https://cloud.githubusercontent.com/assets/7852916/21729536/b26e126c-d408-11e6-8b96-c2ef5ca28aff.png)

**Comment by amanda-phet** [comment]
In the 1/12/17 meeting we decided to make the dots slightly lighter. Here they are using (102, 102, 102) as the shade of gray:

![screen shot 2017-01-16 at 2 54 26 pm](https://cloud.githubusercontent.com/assets/7852916/22000344/daef7442-dbfb-11e6-8257-bfdecac92206.png)

Assigning to @jonathanolson to implement.

**Comment by jonathanolson** [comment]
It looks like in these mock-ups, the ball actually moves past the end of the table (green area) when it moves into a "pocket", correct?

I just want to clarify, as it will require additional changes to the model.

**Comment by amanda-phet** [comment]
>It looks like in these mock-ups, the ball actually moves past the end of the table (green area) when it moves into a "pocket", correct?
I just want to clarify, as it will require additional changes to the model.

The mockups are just dated. Please only change the border to be black and slightly thicker, and add the dots.

**Comment by jonathanolson** [comment]
Changes made.

Also recommended (let me know):

1. Gray pockets instead of black?
2. Having thinner and less noticeable grid lines really looks better in the mock-ups above (can I experiment?)
3. Dragging the border in the predict screen should probably be disallowed, since it immediately hides the table?

**Comment by amanda-phet** [comment]
1. Yes I'm sorry I forgot to specify that change. They should be the same color as the dots (102, 102, 102). 
2. Are the lines white in the sim? Maybe that's why they seem so bold. They are gray in my mockup (168, 168, 168). Please feel free to experiment with thinner and/or gray. 
3. That seems like a simple fix. I assume that also means there won't be any dots.

**Comment by jonathanolson** [comment]
Changes made, let me know how it looks.

> Please feel free to experiment with thinner and/or gray.

Did thinner and gray (let me know if it looks too faint).

> I assume that also means there won't be any dots.

Correct, no dots on it on the predict screen.

**Comment by amanda-phet** [comment]
Looks great!
