### ISSUE TITLE
Stretch dynamic range of color gradient

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#45]
Discussed in 1/12/17 design meeting that @jonathanolson would try to stretch the dynamic range of the color gradients. For example, there is little variation in shades of green when mixing blue and yellow, and not many shades of yellow or blue.

**Comment by jonathanolson** [comment]
Added stretching, let me know if it looks like a good amount, or if it should be tweaked.

**Comment by amanda-phet** [comment]
Looks good to me. @kathy-phet should also look since it initially caught her eye.

**Comment by kathy-phet** [comment]
Looking better.

I'm not sure how challenging it is to compress/stretch, but I think it would be a bit better if you could try the following: 
- further compress the green range between 10:20 to 20:11 (still hard to distinguish a couple of small steps in this region)
- further compress the far blue range between 20:0 and 20:3 (this is also a bit hard)
- further stretch the blue-green range between 20:4 and 20:11 (where the color is changing rapidly)
These are all relative to the *current* color mapping given a (blue):(yellow) ratio.

Caveate - I think this would help with distinguishing colors, but I am not sure!

**Comment by jonathanolson** [comment]
Slightly updated the colors.

While I'm able to now distinguish between all shades of (x,20) and (20,x), I don't think its necessary for this to happen. We have the arrow indicators that can show a difference between similar colors (e.g. 20,19 and 20,20). Additionally, we have 257 unique ratio values (out of 441 different combinations), some of which only have a difference of 0.07% (19,20 and 18,19) which will almost always look almost identical.

**Comment by kathy-phet** [comment]
@jonathanolson - I tried to run from phettest and its not working? Just stays in launch mode with no progress on progress bar?

**Comment by jonathanolson** [comment]
@amanda-phet also noted a similar issue earlier.

Everything seems to be working normally for me after "pull all" (phettest version loading properly now). A bunch of common repositories were out of date (chipper and joist being the most important), so updating the sim repository only would be insufficient.

**Comment by amanda-phet** [comment]
I think it looks really good. I don't want to stretch everything so much that it doesn't feel realistic, because as @jonathanolson says, some of these ratios are actually very close so the paint shades should look similar.

**Comment by jonathanolson** [comment]
@kathy-phet, sorry I had to run a few minutes before 4 today. Should we schedule a call/meeting (I'll be available on campus on Monday) to polish this?

**Comment by kathy-phet** [comment]
Sorry JO -- I'll try to catch you on Monday. Do you have any other meetings?

**Comment by jonathanolson** [comment]
I have a planned call starting ~9:30am about Wicket migration with Matt, not sure how long it would last (if it's long, could fit in time about proportion playground). I may need to leave campus at 1:30pm on Monday.

**Comment by amanda-phet** [comment]
The current color gradient is working well for me. Closing this issue.
