### ISSUE TITLE
Layout and touch areas for larger strings

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/proportion-playground#50]

**Comment by jonathanolson** [comment]
Also do i18n checks and touch areas again.

**Comment by jonathanolson** [comment]
Breaks:

![screen shot 2017-01-19 at 10 39 04 pm](https://cloud.githubusercontent.com/assets/480878/22137418/34cf2b58-de98-11e6-907d-2749b99e41e7.png)
![screen shot 2017-01-19 at 10 40 05 pm](https://cloud.githubusercontent.com/assets/480878/22137427/4443a5fa-de98-11e6-9d8e-44d1dc4227f7.png)

**Comment by jonathanolson** [comment]
@ariel-phet, it looks like the number picker doesn't support maxWidth (what we usually use). Since the dollar sign is translatable, stringTest=long fails above. stringTest=double or really anything fairly short/symbolic works fine:
![screen shot 2017-01-19 at 10 46 53 pm](https://cloud.githubusercontent.com/assets/480878/22137616/5444e058-de99-11e6-8e83-409630aae9da.png)

Should I leave that number picker as-is, or create an issue (and implement) maxWidth handling for number pickers?

**Comment by jonathanolson** [comment]
I take back what I said about stringTest=double above:
![screen shot 2017-01-19 at 10 59 22 pm](https://cloud.githubusercontent.com/assets/480878/22137884/fc46ba1e-de9a-11e6-9c2e-98cf458f8cde.png)

It should be fine if they replace the dollar sign with a single other character though.

**Comment by jonathanolson** [comment]
Resolved all mentioned issues except for the above number picker layout issue.

**Comment by ariel-phet** [comment]
@jonathanolson I think we can leave number picker as is and trust our translators to use a symbol not a long string.

Assigning back to you, just as a reminder to note this for the QA team when you do testing. Feel free to close.

**Comment by jonathanolson** [comment]
Thanks, will do. Closing.
