### ISSUE TITLE
Are the red and green apples different sizes on purpose?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/proportion-playground#51]
The green apple is a bit taller.

**Comment by amanda-phet** [comment]
No, that is a mistake. 

And actually, we intended on using only red apples so that users were comparing identical items (*apples to apples*... ha). 

Can we replace the green ones with red ones?

**Comment by jonathanolson** [comment]
Done (also affects the "show both" switch icon).

Let me know if that looks good.

**Comment by amanda-phet** [comment]
Looks good. Thanks!
