### ISSUE TITLE
Bucket images for paint scene

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/proportion-playground#52]
I don't recall whether it was for the "show both" switch or for the pickers, but I didn't know if we were planning on having the partially discussed buckets, one for each paint color.

**Comment by amanda-phet** [comment]
We did discuss it but I think everything is looking good as it is so I'm not sure we need a paint bucket anywhere. I do have one from Mariah (not the .ai file though) so if we decide we need a paint bucket we can use her image.
