### ISSUE TITLE
Start all ratios on the Predict screen at 5:5

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#53]
Decision from 1/19/17 meeting

**Comment by jonathanolson** [comment]
IIRC, the "predict" button would also be enabled by default at the start?

**Comment by amanda-phet** [comment]
Correct. Thanks for remembering!

**Comment by jonathanolson** [comment]
Reveal button is now always enabled. Does everything for this issue look good?

**Comment by amanda-phet** [comment]
Looks great!
