### ISSUE TITLE
make paint splotch grow/shrink in a less discrete way

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#54]
@jonathanolson will implement a smoother, more continuous growth animation. 

Also, when the splotch contains only 1 unit of paint, the splotch should morph into a paint drop instead of just disappearing.

**Comment by jonathanolson** [comment]
Morphing when dripping is done. In my opinion, the instant "splat" of a balloon is a benefit currently (looks weird if it is slowed down).

Thoughts?

**Comment by amanda-phet** [comment]
Looks great to me!

**Comment by amanda-phet** [comment]
Closing this issue since this is implemented and looks good. Happy to re-open if people have objections.
