### ISSUE TITLE
Add a refresh button on Explore screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#55]
Since clicking the reset-all button returns the user to the necklace scene we decided on 1/19/17 to add a refresh button that just refreshes the scene. 

There is a button like this in Unit Rates and I like the appearance of it quite a bit: 
![screen shot 2017-01-25 at 10 58 40 am](https://cloud.githubusercontent.com/assets/7852916/22302723/503213c0-e2ed-11e6-90a1-8a2b07627a44.png)

It should be smaller than the blue reveal button (on the Predict screen) but in the same location.

**Comment by jonathanolson** [comment]
> It should be smaller than the blue reveal button (on the Predict screen) but in the same location.

Does that mean it would not exist on the Predict screen?

**Comment by amanda-phet** [comment]
That's correct. We decided in the meeting that the predict screen doesn't need it because clicking the spinner feels like a reset because the image disappears.

**Comment by jonathanolson** [comment]
Let me know how it looks and behaves. Resetting the scene included resetting "show both", but it may be beneficial to not reset that.

**Comment by amanda-phet** [comment]
I agree it should not reset the toggle, only the spinners. 

If we are going to use this sort of refresh button in sims we might want to discuss the appearance of it with some more phet team members. Hopefully there will be time at Status to bring it up.

**Comment by jonathanolson** [comment]
Discussion would be good. It's the same icon as reset-all, and sometimes those two buttons are right next to each other, so it may be confusing.

Reassigned so it doesn't reset the show-both switch.

**Comment by jonathanolson** [comment]
Changed so it just resets each ratio (ignoring things such as "show both").

**Comment by arouinfar** [comment]
@amanda-phet @jonathanolson there was quite a bit of discussion around the use of ResetButton in Unit Rates in https://github.com/phetsims/unit-rates/issues/86.  I initially had reservations about having a ResetButton AND ResetAllButton both visible on screen, however, there didn't turn out to be any usability issues in interviews. MOTHA also uses a ResetButton:
![image](https://cloud.githubusercontent.com/assets/8419308/25243392/1ebe3fa2-25ba-11e7-9966-8e9dafc37ee3.png)

Both instances of ResetButton have been gray and a bit smaller than ResetAllButton. That approach seems to have worked so far, but we should probably discuss it before it becomes a truly common component.

**Comment by amyh-phet** [comment]
@amanda-phet   I'm also okay with using this reset button.  As @arouinfar points out, we will need to use a version of it in MOTHA to reset the spectrometer.

**Comment by amanda-phet** [comment]
Will keep the button as-is for now but would still like to bring this up at status at some point in case any team members have ideas for rules about how/when to use this button and if the appearance should be changed.
