### ISSUE TITLE
Add Color profile handling

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/proportion-playground#57]
Should allow easy editing.

**Comment by jonathanolson** [comment]
Partial progress, see http://phettest.colorado.edu/proportion-playground/proportion-playground-colors.html

**Comment by jonathanolson** [comment]
Pretty sure I hit everything that's relevant (make sure to pull before testing).

Give it a try, and see what background color (or other color changes) would be an improvement?

**Comment by amanda-phet** [comment]
This can be closed since this feature has been working just fine.
