### ISSUE TITLE
Necklace performance

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/proportion-playground#58]
Slows down when getting to 20,20. Will check during review/cleanup of that code.

**Comment by phet-steele** [comment]
The necklace screen can very reliably crash an iPad when playing near 20,20 with both necklaces showing.

**Comment by jonathanolson** [comment]
@phet-steele, can you check to see if the performance on http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.21/proportion-playground_en.html (dev.21) is better than http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.20/proportion-playground_en.html (dev.20)?

**Comment by jonathanolson** [comment]
Testing on an iPad shows that the left-most necklace is WAY slower than the right-most one.

**Comment by jonathanolson** [comment]
WebGL rendered necklace seems to sometimes help performance, and on my devices looks fairly indistinguishable with the regularly rendered one:
![screen shot 2017-04-12 at 8 31 52 pm](https://cloud.githubusercontent.com/assets/480878/24987818/2d8992c6-1fbf-11e7-9612-22e08099ec99.png)

But testing on Lave (iPad) showed that switching to the 1st screen had some latency (presumably compiling shaders) and while sometimes performance was fast, it was still slightly laggy.

It also gets out of sync, see https://github.com/phetsims/scenery/issues/611.

@phet-steele, can you confirm if performance seems to be full-speed on master right now (built), or if you see the described slow-downs? Also do you see any rendering issues like sharpness/blurryness?

**Comment by jonathanolson** [comment]
Deployed http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.22/proportion-playground_en.html, with the WebGL Necklace disabled due to https://github.com/phetsims/scenery/issues/611.

@ariel-phet and @phet-steele, can I get a check of this version to determine whether this is "acceptable on the iPad"?

I was working on getting the Scenery/Kite WebGL path support in order to draw the necklace string (so that it would be synchronized with the beads), but since most of that work has been delayed, it would probably take a good chunk of time to get it completed.

If performance is unacceptable, I can look into downgrading the appearance of the necklace on iOS (removing gradients should most likely help).

**Comment by jonathanolson** [comment]
@phet-steele mentioned crashing issues on startup (presumably memory-related). This can be worked around by disabling WebGL for balloon display, since it can't have things in-between WebGL at the moment (missing Path/Text current support).

Deploying http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.23/proportion-playground_en.html (should crash less, but balloon flying performance is probably lower).

**Comment by phet-steele** [comment]
@jonathanolson, dev.23 performance is not great, but acceptable and with no crashes under normal use. I believe @ariel-phet agreed with me the other day he was in the office.

**Comment by jonathanolson** [comment]
Ok, closing. WIth future WebGL changes, could resurrect the higher-performance version in the future.
