### ISSUE TITLE
Beads too close together on necklace

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#6]
@kathy-phet said:

I was using it on my phone, and noticed the beads are really tight to each other and sometimes a bit overlapping. I'm wondering if a little space might help with counting the beads. Caveate that it might look fine on a full screen.

**Comment by samreid** [comment]
In the above commit I made the beads smaller and further apart.  Putting on hold until next version for testing.

**Comment by samreid** [comment]
Fixed, so closing.  Everything can be reviewed in next version.

**Comment by samreid** [comment]
@phetsims/beth-stade said:

> I preferred the brighter colors and size of necklace before - was there an issue with larger beads?

@kathy-phet and @amanda-phet said they would discuss the latest version, I'll leave it up to them to consider @phetsims/beth-stade's comment.

**Comment by amanda-phet** [comment]
This issue seems dated. Closing.
