### ISSUE TITLE
Only one billiards table animates upon switching between single and double view.

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/proportion-playground#65]
For phetsims/tasks#794
Seen on OS X  10.11.6, Safari

When playing with the billiards screen, I noticed that if you switch from the single view to the double view, only the second billiard table will animate again. I imagine the desired behavior is that they should only animate again when the numbers are changed or if the reveal button is toggled, so when you switch between views here, neither of them should animate. 
![propplayground](https://cloud.githubusercontent.com/assets/11947677/23873143/9c1c928c-07f6-11e7-98e5-8f8c1437d2c9.gif)

Troubleshooting information (do not edit):
Name: ‪Proportion Playground‬
URL: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.19/proportion-playground_en.html
Version: 1.0.0-dev.19 2017-03-03 19:51:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7
Language: en-us
Window: 1248x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.51)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"e0b1c391","branch":"master"},"babel":{"sha":"dd41f374","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"43ca9ac4","branch":"master"},"dot":{"sha":"16c2f26b","branch":"master"},"joist":{"sha":"695d3638","branch":"master"},"kite":{"sha":"f4c67cff","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"49b5cb0d","branch":"master"},"proportion-playground":{"sha":"06f03e67","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"04879a99","branch":"master"},"scenery-phet":{"sha":"45adfa82","branch":"master"},"sherpa":{"sha":"98566566","branch":"master"},"sun":{"sha":"dc8dcfbf","branch":"master"},"tandem":{"sha":"45e9ee17","branch":"master"}}

**Comment by jonathanolson** [comment]
@amanda-phet, should the second billiards table essentially "pause" when the user switches away, continue animating (when it's not seen), or should we have some form of "starting over" like happens now?

**Comment by amanda-phet** [comment]
I like Ben's suggestion here. It does seem odd the way it's currently behaving. Is that a major change, @jonathanolson ?

**Comment by jonathanolson** [comment]
> Is that a major change

No, shouldn't be.

Which of the options would be preferred, should it "pause" when the user switches off showBoth (when they turn showBoth on, it starts animating from where it was before), or should it continue animating?

**Comment by amanda-phet** [comment]
I was imagining that it would continue animating (even if not in view) so that both tables show the same state when toggling back and forth.

**Comment by jonathanolson** [comment]
Implemented in the above commit. I made the assumption that it shouldn't ever start the animation in the background (when hidden), but it will continue to step the hidden billiards board once it is started.

Let me know if this feels like the desired behavior?

**Comment by amanda-phet** [comment]
Looks great to me. Thanks!

**Comment by phet-steele** [comment]
@amanda-phet @jonathanolson now hold on one second 😄! One of the things @brroberts1231 said was maybe overlooked:
> I imagine the desired behavior is that they should only animate again when the numbers are changed **_or if the reveal button is toggled_**

Animations do not always restart upon toggling the reveal button. The user has to change a value first, so we've now lost the ability to watch the animation repeatedly. It's not necessarily the most important feature, but it's a nice one I see no reason to take away. To elaborate:

In dev.19, repeated clicks of the reveal button cancelled the ongoing animation and restarted it. This allowed you to watch your experiment multiple times:
![prp03](https://cloud.githubusercontent.com/assets/5863899/25496153/2298e392-2b3d-11e7-822c-99151820ec90.gif)


Now in dev.25, animations do not restart until values are changed. This does make it quite hard in the case where you only want to change one table and watch them both animate. Only one will animate (the one you changed):
![prp04](https://cloud.githubusercontent.com/assets/5863899/25496168/2c353022-2b3d-11e7-89ce-2ddfeda16c9e.gif)

Can we bring this behaviour back? Again, it doesn't seem critical, more of a "quality of life" feature.

**Comment by amanda-phet** [comment]
It is definitely not critical, and at this point really need to get the sim finished off so I'm going to say we can skip this quality-of-life feature. The animation is not necessary to compare two patterns. Instead, it's there to help students make predictions about the final state and update their predictions as they watch. This is still possible for the new table, and still allows them to compare the two final patterns.
