### ISSUE TITLE
White paint spinner doesn't have a "clickable" cue

### ISSUE THREAD

**Issue by phet-steele** [phetsims/proportion-playground#66]
The white paint's spinner has no mouse highlight ***on hover*** (or it's just white). The video below shows my mouse as a yellow dot:

![prp01](https://cloud.githubusercontent.com/assets/5863899/24007040/1d09a248-0a33-11e7-87d5-78bec4df3f67.gif)

Why not make the highlight the grayish color that appears when clicking on the spinner? (at the end of the video)

Seen on macOS 10.12.3 Chrome and lots of other things. For phetsims/tasks/issues/794.
URL: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.19/proportion-playground_en.html
Version: 1.0.0-dev.19 2017-03-03 19:51:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1920x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"e0b1c391","branch":"master"},"babel":{"sha":"dd41f374","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"43ca9ac4","branch":"master"},"dot":{"sha":"16c2f26b","branch":"master"},"joist":{"sha":"695d3638","branch":"master"},"kite":{"sha":"f4c67cff","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"49b5cb0d","branch":"master"},"proportion-playground":{"sha":"06f03e67","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"04879a99","branch":"master"},"scenery-phet":{"sha":"45adfa82","branch":"master"},"sherpa":{"sha":"98566566","branch":"master"},"sun":{"sha":"dc8dcfbf","branch":"master"},"tandem":{"sha":"45e9ee17","branch":"master"}}

**Comment by jonathanolson** [comment]
Presumably this would be handled in the common picker code, and may change other sims' picker highlighting.

@amanda-phet, thoughts?

**Comment by amanda-phet** [comment]
It seems inconsistent on one hand but it also doesn't bother me too much because the paint is white, so it also performs as expected. I'd rather not handle it right now but it might be something to discuss with the other sim designers for a future change to the common code picker.

**Comment by phet-steele** [comment]
@amanda-phet I think this is less about the picker being "correct" since the paint is white, and more about the fact that this spinner has the potential to always look disabled.

**Comment by amyh-phet** [comment]
I agree that it seems inconsistent. @amanda-phet  Have you interviewed on this sim yet?  I'm thinking if users haven't had an issue figuring this out, then I would leave the behavior as is.

**Comment by arouinfar** [comment]
> It seems inconsistent on one hand but it also doesn't bother me too much because the paint is white, so it also performs as expected.

Agreed @amanda-phet, though I do still lean towards the gray shading because it feels more consistent. If there haven't been any issues that cropped up in interviews, I'd be fine with leaving the spinner as-is, though.

**Comment by amanda-phet** [comment]
No issues in interviews, but b&w wasn't used very much. 

I think we should keep it as-is and if we make changes to white spinners on a universal scale then the changes will apply to this sim at that time. Right now, I would prefer to focus on getting this sim out the door.
