### ISSUE TITLE
Equality arrows turn black prematurely when rapidly adding/subtracting paint

### ISSUE THREAD

**Issue by phet-steele** [phetsims/proportion-playground#67]
The video demonstrates each step of the procedure to highlight three different use cases:

1. Set up 20,18 and 20,20. Increment the 18 up to 20 slowly, waiting for the balloon to land each time. Everything works well in this scenario.
2. Start over at the same proportions. This time, increment 18 up to 20 quickly. There will be a slight moment (don't blink) where the equality arrows along the center will be black before they are aligned with each other.
3. Start over with 20,0 and 20,20. hold down the spinner for 0 until it reaches 20. This is a more dramatic use case for step 2 where the equality arrows turn black MUCH earlier than they should.

![prp02](https://cloud.githubusercontent.com/assets/5863899/24010927/e10f2298-0a3e-11e7-9fda-a515721a9dcc.gif)

Seen on macOS 10.12.3 Chrome and lots of other things. For phetsims/tasks#794.
URL: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.19/proportion-playground_en.html
Version: 1.0.0-dev.19 2017-03-03 19:51:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1920x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"e0b1c391","branch":"master"},"babel":{"sha":"dd41f374","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"43ca9ac4","branch":"master"},"dot":{"sha":"16c2f26b","branch":"master"},"joist":{"sha":"695d3638","branch":"master"},"kite":{"sha":"f4c67cff","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"49b5cb0d","branch":"master"},"proportion-playground":{"sha":"06f03e67","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"04879a99","branch":"master"},"scenery-phet":{"sha":"45adfa82","branch":"master"},"sherpa":{"sha":"98566566","branch":"master"},"sun":{"sha":"dc8dcfbf","branch":"master"},"tandem":{"sha":"45e9ee17","branch":"master"}}

**Comment by jonathanolson** [comment]
@phet-steele can you verify my fix?

**Comment by phet-steele** [comment]
Looks bueno.
