### ISSUE TITLE
1/19 and 1/20 both cost $0.05

### ISSUE THREAD

**Issue by samreid** [phetsims/proportion-playground#7]
In the apple scene, the design doc suggested to show price per apple to the nearest penny.  However, with 1/19=0.0526 which rounds to $0.05 as well. 

The same problem occurs for other numbers as well.

@kathy-phet @ariel-phet @amanda-phet @jonathanolson @krhensberry @phetsims/beth-stade how do you recommend to handle this (if anything)?

**Comment by amanda-phet** [comment]
This has been discussed in Unit Rates and we are fine with leaving this how it is.
