### ISSUE TITLE
Change visibility button color to yellow

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/proportion-playground#72]
Please change the visibility button on the Predict screen to be yellow. The standard PhET yellow button color should be fine. I tried to preview this using http://phettest.colorado.edu/proportion-playground/proportion-playground-colors.html but the button isn't listed.

**Comment by jonathanolson** [comment]
Changed to the standard color. It wasn't listed (sorry), because it actually used the common-code button default color.

**Comment by jonathanolson** [comment]
Will have a commit soon making it changeable. Is that the color you were talking about? (It's what developers said was the most likely standard yellow).

**Comment by amanda-phet** [comment]
Thank you that does look good. I wanted that button to be visible and it definitely is :)
