### ISSUE TITLE
Center of the paint image is not static

### ISSUE THREAD

**Issue by phet-steele** [phetsims/proportion-playground#73]
@jonathanolson it looks like the paint image does not scale symmetrically around its center and/or the center moves when paint is added/removed. This is apparent when watching the location of the drips at different paint sizes. Using the edges of the spinners as a reference, notice that as the splotch decreases in size, the origin of the drips moves to the right with respect to the entire screen.

Really obvious at the moment this gif loops:
![prp05](https://cloud.githubusercontent.com/assets/5863899/25503349/4ae168a0-2b57-11e7-8fcc-8807ab182fe3.gif)

This doesn't feel like a large issue, but is somewhat visually unappealing.

Seen on macOS 10.12.4 Chrome. For phetsims/tasks/issues/827.
URL: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.25/proportion-playground_en.html
Version: 1.0.0-dev.25 2017-04-26 18:31:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"f475e68c","branch":"master"},"babel":{"sha":"03e6693c","branch":"master"},"brand":{"sha":"f4b72cac","branch":"master"},"chipper":{"sha":"3061f107","branch":"master"},"dot":{"sha":"57936fff","branch":"master"},"joist":{"sha":"899daf14","branch":"master"},"kite":{"sha":"0cc5b620","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"d0ffe176","branch":"master"},"proportion-playground":{"sha":"831167f6","branch":"master"},"query-string-machine":{"sha":"e7055778","branch":"master"},"scenery":{"sha":"57106ffb","branch":"master"},"scenery-phet":{"sha":"6dc1a064","branch":"master"},"sherpa":{"sha":"0e326d54","branch":"master"},"sun":{"sha":"3967c777","branch":"master"},"tandem":{"sha":"30603e66","branch":"master"}}

**Comment by jonathanolson** [comment]
Should be fixed in master with the above commit. @phet-steele can you confirm?

**Comment by phet-steele** [comment]
Beautiful @jonathanolson!

**Comment by phet-steele** [comment]
@jonathanolson actually, the paint drips are not centered anymore at low splotch areas. Is it possible to move the drip's "center" to the right a bit more to agree with the splotch center?

dev.27: drips nice and centered with splotch
![pp07](https://cloud.githubusercontent.com/assets/5863899/26366854/cfddf3a0-3fa9-11e7-8ab0-0f9ab35246d1.gif)

rc.1 & 2: drips offset too far left
![pp08](https://cloud.githubusercontent.com/assets/5863899/26366907/06a50108-3faa-11e7-9727-610db57ade76.gif)


Again, this really only matters at low splotch areas. We don't need to have the drips move with the center of the splotch at all times. Sorry for not noticing earlier!

**Comment by jonathanolson** [comment]
@phet-steele, can you test this in master? I'll move this over to the release branch, as I believe the code that I had positioning the splotch was a bug.

**Comment by phet-steele** [comment]
@jonathanolson the paint looks great now!
