### ISSUE TITLE
The case of the perplexing crash

### ISSUE THREAD

**Issue by phet-steele** [phetsims/proportion-playground#74]
@jonathanolson @ariel-phet here's the most recent procedure to MAYBE make 1.0.0-dev.26 crash on iPad 2 iOS 9.3.5:

1. Open sim (maybe a crash here)
2. Select Explore, single necklace
3. Increment both sliders to 20, using fire and hold (I used two fingers each holding a spinner, but I recall this as being unnecessary in dev.25).
4. You may crash on your way to 20/20, or at 20/20. You may instead crash a few seconds after reaching 20/20. If not, reload and try again. You may even crash when reloading to try again. As you can see, there are numerous situations in which dev.25 and dev.26 have crashed, but all seem tied to the necklace. Good luck reproducing!...because I can't.

**Comment by jonathanolson** [comment]
Does it give any reasons in XCode if tethered during the crash? What does the typical iOS memory usage for the sim look like?

**Comment by jonathanolson** [comment]
Will plan to look in person tomorrow, as I'm unable to get Lave (9.3.5 iPad 2) to crash.

**Comment by jonathanolson** [comment]
I found (and fixed) an issue that was causing the creation of many excess canvases and svg elements, which happens close to startup. I've published http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.27/proportion-playground_en.html with the fix.

This will hopefully prevent the crashes, and also offers somewhat of a performance improvement on the iPad 2 I have with me.

@phet-steele, can you test this for crashes?

**Comment by phet-steele** [comment]
Unable to have 1.0.0-dev.27 crash. Also haven't made rc.1 crash, will reopen if it does.
