### ISSUE TITLE
layout bug with stringTest=long

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#75]
Related to #69 (code review).

Label falls outside the Screen's layoutBounds. 

![screenshot_256](https://cloud.githubusercontent.com/assets/3046552/25818140/d546e1c2-33e6-11e7-8bf5-96dbd79c3db7.png)

**Comment by jonathanolson** [comment]
Ahh, I forgot to add a maxWidth to the price tag (that's pushing it out):
![screen shot 2017-05-09 at 11 13 47 am](https://cloud.githubusercontent.com/assets/480878/25863298/9c7c0292-34a8-11e7-9d1d-2c65490e1c2a.png)

**Comment by jonathanolson** [comment]
Fixed the max width (and translated the apple string). Everything should fit now:
![screen shot 2017-05-09 at 11 20 18 am](https://cloud.githubusercontent.com/assets/480878/25863557/86cc03c4-34a9-11e7-9353-44b7805be91e.png)
