### ISSUE TITLE
non-standard keys for Screen names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#76]
Related to #69 (code review).

From the code-review checklist:

> Screen names should use camelcase, like so `screen.screenName`

Screen names are currently:

```js
  "explore": {
    "value": "Explore"
  },
  "predict": {
    "value": "Predict"
  },
```

Keys should be `screen.explore` and `screen.predict` respectively.

**Comment by jonathanolson** [comment]
Fixed in commit above.
