### ISSUE TITLE
document paint-gradient-colors.html and blue-green-gradient.png

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#77]
Related to #69 (code review).

Quite by accident, I discovered that assets/paint-gradient-colors.html looks like it was used to generate blue-green-gradient.png.   I searched for those file names, not found, so no idea what they are used for, or how they might be useful to future maintainers.  Please document, perhaps in implementation-notes.md.

**Comment by jonathanolson** [comment]
Looks unused. I'll plan to remove them.

**Comment by pixelzoom** [comment]
@jonathanolson removed these files in https://github.com/phetsims/proportion-playground/issues/78.  

Closing.
