### ISSUE TITLE
clean up assets directory 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#78]
Related to #69 (code review).

The assets directory needs to be cleaned up.   It should be straightforward for future maintainers to locate the artwork that was actually used in the sim. 

For example:

- [ ] fruitstand.ai, fruitstand2.ai - 2 fruit stands, neither of which appears to have been used. Delete these?

- [ ] ballons.ai, paint-balloons.ai, paint-scene.ai - 3 version of the paint balloons. Looks like paint-balloons.ai is the relevant one? If so, delete the other 2.

- [ ] objects.ai - With the exception of the apple, this looks like a bunch of objects that were never actually used in the sim.  Pull out apple into apple.ai, delete the rest.

- [ ] apple-scene-artwork.ai - Again, stuff that wasn't used (coin), or stuff that appears in other .ai files (crate.ai, apple.ai).

**Comment by pixelzoom** [comment]
Presumably the apple in this sim is the same as the one in unit-rates. So rather than create apple.ai, you could put a note in images/license.json indicating that apple.png was create using unit-rates/assets/apple.ai.

**Comment by jonathanolson** [comment]
> Presumably the apple in this sim is the same as the one in unit-rates.

Or we should move the Apple to a common location (scenery-phet?)

**Comment by jonathanolson** [comment]
paint-scene.ai is for the scene icon (used), so I'll keep it also.

**Comment by pixelzoom** [comment]
> Or we should move the Apple to a common location (scenery-phet?)

Well.... If we moved to scenery-phet, we should move both the asset (applie.ai) and the image (apple.png).  Do we have any precedent for putting resources in a common-code repo that aren't used by code in that repo? 

Given the amount of image copying that seems to go on between repos, I'm inclined to just ignore this for now.

**Comment by pixelzoom** [comment]
> paint-scene.ai is for the scene icon (used), so I'll keep it also.

Indeed. I didn't notice that it corresponds to paint-scene.png.

**Comment by jonathanolson** [comment]
> Do we have any precedent for putting resources in a common-code repo that aren't used by code in that repo?

As part of https://github.com/phetsims/make-a-ten/issues/231, I moved hand.png and hand.ai from states-of-matter to scenery-phet. That's been the only other case of duplicated images I was aware of.

> Given the amount of image copying that seems to go on between repos, I'm inclined to just ignore this for now.

Feels unclean to me, however the images are of different sizes. I'd take a shot at having both sims use the same image, but you might need specific (even-numbered) dimensions for your image?

**Comment by jonathanolson** [comment]
Current artwork map (upcoming commit):

- crate-front.png/crate-back.png => crate.ai
- paint-scene.png => paint-scene.ai
- (all the balloons) => paint-balloons.ai
- apple-red.png => unit-rates' apple.ai (may refactor to common usage)
- coin.png => new coin.ai (extracted from apple-scene-artwork.ai)

**Comment by pixelzoom** [comment]
Looks good.

If you decide to refactor the apple, I advise against touching unit-rates/images/apple.png.  The relative sizes of PNG files are important in unit-rates, because there's a uniform scale (`URConstants.SHOPPING_ITEM_IMAGE_SCALE`) applied to all "item" images.  So if you change the dimensions of apple.png, its unlikely to be a good experience.

**Comment by pixelzoom** [comment]
Re "the apple"... @jonathanolson and I discussed on Skype, and decided that the safest/simplest thing to do was to copy unit-rates/assets/apple.ai to proportion-playground/assets/.
