### ISSUE TITLE
review model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#79]
Related to #69 (code review).

From the code-review checklist:

> - [ ] Does model.md adequately describe the model, in terms appropriate for teachers?

@amanda-phet Would you please review [model.md](https://github.com/phetsims/proportion-playground/blob/master/doc/model.md)?  Does it have an appropriate level of detail, and the correct language, for its audience?

**Comment by pixelzoom** [comment]
@jonathanolson I'm having trouble groking this sentence:

> It's equivalent to traveling across a (width/gcd)x(height/gcd) rectangle from one corner to another, thus with (width+height)/gcd bumps/endpoints, and a total distance of width*length*sqrt(2)/gcd^2.

... specifically the "thus with (width+height)/gcd bumps/endpoints" part.

**Comment by jonathanolson** [comment]
Clarified wording. @pixelzoom, is that better? It was definitely confusing beforehand.

**Comment by pixelzoom** [comment]
Yep, that makes much more sense, thanks.

Back to @amanda-phet to decide if model.md is sufficient for teachers.

**Comment by amanda-phet** [comment]
This is for teachers? I think that the wording is fine and understandable, but I wouldn't add this detail to something like teacher tips. 

I'm not totally sure what this model.md documentation is really for. I've never reviewed this in the past.

**Comment by jonathanolson** [comment]
I think (?) it's purpose is so we can direct teachers who ask questions about how the model works to that file (or refer to it when asking questions)?

**Comment by amanda-phet** [comment]
I think it is clear enough for this purpose.

**Comment by pixelzoom** [comment]
model.md provides a high-level description of the model. It's intended for audiences
that are not necessarily technical.  It's what we point people to who ask "how does the model work?"
