### ISSUE TITLE
NecklaceLayout uses DOT.Random

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#81]
Related to #69 code review.

> - [ ] Check that random numbers are generated using `phet.joist.random` ...

In `NecklaceLayout`:

```js
64 var random = new Random( { seed: seed } );
```

Does `NecklaceLayout` have a legitimate reason to be using its own instance of `Random`?  If so, document it. If not, convert to `phet.joist.random`.

**Comment by jonathanolson** [comment]
> Does NecklaceLayout have a legitimate reason to be using its own instance of Random?

It has the requirement that the stream of random numbers needs to be the same for every equivalent ratio, so that (10,8) has the same "distortion" as (20,16). Somewhat mentioned in the function's comment:

```
   * This repulsion should be the same for necklaces with the same proportion (and is not used if there is 0 of one
   * bead type), so a seed is generated from the ratio of the bead counts, and repulsion points are shared for every
   * layout that has the same seed.
```

**Comment by pixelzoom** [comment]
@jonathanolson I added documentation to the instantiation of Random, see if it's OK with you.

**Comment by jonathanolson** [comment]
Sounds great, thanks!
