### ISSUE TITLE
relocate ProportionPlaygroundQueryParameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#82]
Related to code review #69.

From the checklist:

>  - [ ] Are sim-specific query parameters (if any) identified and documented in one .js file in js/common/ or js/ (if there is no common/)? The .js file should be named `{{REPO}}QueryParameters`, for example `ArithmeticQueryParameters` for the aritmetic repository.

The sim does have `ProportionPlaygroundQueryParameters`.   But it's located at the top level of `js/`, and I was expecting to find it in `js/common/`.   This appears to be the only multi-screen sim that doesn't locate this file in `js/common/`, so suggested to relocate it.  (Single-screen sims put this file in the directory for their single screen, since there's no common directory.)

**Comment by jonathanolson** [comment]
Moved in above commit.
