### ISSUE TITLE
code formatting 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#83]
Related to code review #69.

From the checklist:

> Is the code formatted according to PhET conventions? See phet-idea-code-style.xml for IntelliJ IDEA code style.

"Reformat code" in IDEA changes 26 files.   Many (all?) are places where @jonathanolson's indentation preferences don't match phet-idea-code-style.xml.

**Comment by pixelzoom** [comment]
I took the liberty of making the formatting changes that didn't seem to be related to @jonathanolson's indentation preferences, see above commit.

13 files remain that don't match PhET formatting, and they are all indentation differences like this one in AppleGroup.js.   @jonathanolson's formatting is:

```js
    SceneRatio.call( this, visibleProperty, controlsVisibleProperty,
                     this.totalCostProperty, ProportionPlaygroundConstants.APPLE_TOTAL_COST_RANGE,
                     this.numberOfApplesProperty, ProportionPlaygroundConstants.APPLE_COUNT_RANGE );
```

IDEA formatting is:

```js
    SceneRatio.call( this, visibleProperty, controlsVisibleProperty,
      this.totalCostProperty, ProportionPlaygroundConstants.APPLE_TOTAL_COST_RANGE,
      this.numberOfApplesProperty, ProportionPlaygroundConstants.APPLE_COUNT_RANGE );
```

@jonathanolson up to you whether to address this.

**Comment by jonathanolson** [comment]
I currently don't have a working IDEA installation. Can you apply the formatting changes to master and I'll review? The above mentioned change is acceptable (but similar changes where alignment is more helpful, like with Matrix3 parameters, may need fixing).

**Comment by pixelzoom** [comment]
Remaining IDEA formatting issues pushed.

**Comment by jonathanolson** [comment]
I'll want to fix the code-comment positioning in SceneRatioControl.

Otherwise I don't care enough about the other changes to come up with a preferred code formatting solution.

**Comment by jonathanolson** [comment]
Applied the one fix. I believe this is safe to close, let me know if there's something else.
