### ISSUE TITLE
TODO items with no associated GitHub issue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#85]
Related to code review #69:

> - [ ]  Are there any TODO or FIXME comments in the code? They should be addressed or promoted to GitHub issues.

The sim currently has 14 TODO items that do not have associated GitHub issues.

**Comment by jonathanolson** [comment]
I swear I had removed some of these on one of my devices (e.g. the "TODO: Isolate into six colors that don't have names?" where I decided it was fine and removed the comment).

I'll check into whether I have isolated commits somewhere, but I don't think I made any significant changes. I'll plan to have these resolved.

**Comment by jonathanolson** [comment]
Only one TODO left, referencing https://github.com/phetsims/proportion-playground/issues/71.

Any TODO change of significance references this issue (I think there was one change that removed an irrelevant TODO not tagged here).

**Comment by pixelzoom** [comment]
Looks great. Closing.
