### ISSUE TITLE
comment refers to PropertySet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#86]
Related to code review #69:

> - [ ] The simulation should use Property instead of PropertySet

`ProportionPlaygroundColorProfile` refers to `PropertySet`:

```js
20 // NOTE: This is NOT provided to clients directly, but is passed to the PropertySet constructor.
```

**Comment by jonathanolson** [comment]
ColorProfile doesn't use PropertySet anymore, I'll update the comment.

**Comment by jonathanolson** [comment]
Fixed, and improved documentation.
