### ISSUE TITLE
should dt be capped in the view?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#87]
Related to code-review #69:

> - [ ]  Is the timestep dt capped appropriately?

`dt` is capped in the model (see `ProportionModel.step`), but not in the view (`ProportionScreenView.step`).   If that's OK, then it would be useful to have either (a) a comment in the code that says why it's not capped in the view, and/or (b) a note in implementation-notes.md.

**Comment by jonathanolson** [comment]
@pixelzoom, I'd like your thoughts on whether it should be capped. It's just used for somewhat ephemeral animations (the balloons and drips, which both go away quickly), so I figured it would be somewhat preferred if those animations are fully finished when someone "tabs back" to the sim.

**Comment by pixelzoom** [comment]
I don't have a lot of experience with capping `dt`, first time I've had to do so was in unit-rates, and I did so only in the model.  So I would say "your call, just document what you decide".

**Comment by jonathanolson** [comment]
Uncapped DT, documented in above commit.

**Comment by jonathanolson** [comment]
Clarification: View dt being kept as uncapped. Model dt is capped.
