### ISSUE TITLE
billards table?...

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#90]
Related to code review #69... sort of.

I played around with the sim before reviewing the code.  I never recognized the "billiards" scene until I started reading the code.    

Perhaps it's because the billiards table is missing 2 of it's standard 6 pockets (the 2 side pockets are missing), or the typical wood edge, or the rounded corners, or....

Here's an example of a cartoonish billiards table:

![pool_table](https://cloud.githubusercontent.com/assets/3046552/25825259/9b4e994c-33ff-11e7-9b6d-06cba634f97f.jpg)

I'm not saying that it should look exactly like a real billiards table.  But it concerns me that there weren't enough visual cues for me to recognize it.

**Comment by pixelzoom** [comment]
Here's what it looks like in the sim.  I realize that this is effectively a 2D graph.  But I never made it past "graph with point", never made the connection to billiards. 

![screenshot_258](https://cloud.githubusercontent.com/assets/3046552/25825358/05aea3cc-3400-11e7-8f17-2ea555976b8a.png)

**Comment by jonathanolson** [comment]
At least rounding the outside corners might be a nice visual touch.

I believe I also didn't immediately get the billiards concept visually (even with a brown border, e.g. http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-dev.10/proportion-playground_en.html), but I'm also don't think the reference is critical.

**Comment by amanda-phet** [comment]
The reference is not critical, that is correct. In interviews, when specifically asked about it they did not know this was a billiards table (but understood the logic of the path). However, students spent more time on this scene than any other scene, as they were really interested in the patterns formed. 

I'm ok with rounding the corners. Adding middle pockets doesn't make sense because the ball can't exit there, and could be strange if the ball bounces on that part of the wall but doesn't go in the pocket.

**Comment by pixelzoom** [comment]
My 2 cents... Rounded corners and a brown border (as @jonathanolson pointed to in 1.0.0-dev.10) would be simple and effective improvements. 

 1.0.0-dev.10:

![screenshot_259](https://cloud.githubusercontent.com/assets/3046552/25869417/7691672e-34bd-11e7-8f94-91fba444b874.png)

**Comment by jonathanolson** [comment]
I'll commit rounded corners, however I wasn't trying to recommend a border color (still uncertain). I might test some color combinations to see if I can come up with any improvements.

**Comment by jonathanolson** [comment]
Current colors:
![proportion-playground-current-colors](https://cloud.githubusercontent.com/assets/480878/25870521/8fac2c36-34c1-11e7-8cae-77a32aa96952.PNG)

An initial attempt at color changes if we want a more 'billiards' like appearance:
![proportion-playground-potential-colors3](https://cloud.githubusercontent.com/assets/480878/25870604/edcc719a-34c1-11e7-92e6-322c0334ac91.PNG)

billiardsInside: 15,102,34
billiardsBorder: 85,55,0
billiardsPocket: 0,0,0
billiardsGripDots: 190,190,190

**Comment by jonathanolson** [comment]
I also prefer a re-colored ball (to look like a cue ball):
![proportion-playground-potential-colors4](https://cloud.githubusercontent.com/assets/480878/25870732/6da23f6c-34c2-11e7-96c2-8267576d544d.PNG)

billiardsBallHighlight: 255,255,255
billiardsBallMain: 224,224,224

**Comment by pixelzoom** [comment]
https://github.com/phetsims/proportion-playground/issues/90#issuecomment-300289058 (immediately above) looks like a nice improvement to my eye.

**Comment by amanda-phet** [comment]
I'm not sure why we changed the border to black... perhaps it was to make the table "pop" as Ariel likes to say? I looked in the meeting notes and the github issue and there is no reason stated, and my memory is not what it used to be ;) 

I like the new look. I'm not sure why the ball ever got a yellow glow (perhaps to make it look more round?) but it was always supposed to look white. 

All of the changes in the above comment look great. Now if I reference this table as a "billiards" table in the teacher tips, it should (hopefully) make sense to teachers.

**Comment by pixelzoom** [comment]
Making the ball white certainly makes it look more like a cue ball.

**Comment by amanda-phet** [comment]
@jonathanolson please feel free to commit the changes.

**Comment by jonathanolson** [comment]
On master, let me know if there should be any additional tweaks.

**Comment by pixelzoom** [comment]
Looks great - icons, everything.  @amanda-phet feel free to close if you don't have any additional tweaks.

**Comment by amanda-phet** [comment]
Yup, everything looks good!
