### ISSUE TITLE
anti-pattern for propagating options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#91]
I see this pattern in a couple of places, but here's an example in `BilliardsTableControl`:

```js
function BilliardsTableControl( ..., options ) {

  SceneRatioControl.call( this, ..., {
    // some options
  } );

  options = _.extend( {
    // some options
  }, options );

  // ... bunch of other stuff ...

  this.mutate( options );
}
```

Passing one set of options to the supertype constructor, then passing another set of options to `mutate` is (imo) an anti-pattern.  And it's rarely necessary to do this.

Other places where this anti-pattern appears:

• RevealButton (very unnecessary)
• AppleGraphNode
• BilliardTableIcon (again, very unnecessary)
• GradientIndicatorNode

**Comment by pixelzoom** [comment]
Related to code review #69.

**Comment by jonathanolson** [comment]
I guess I'd like to understand more about how this is an anti-pattern. Is it the fact that the "default options" in the extend aren't used by the supertype? Say you have an example:

```js
function ExampleNode( options ) {
  Node.call( this );

  options = _.extend( {
    something: false
  }, options );

  if ( something ) {
    this.addChild( new SomethingNode() );
  }

  this.mutate( options );
}
```
It's functionally different from:
```js
function ExampleNode( options ) {
  options = _.extend( {
    something: false
  }, options );

  Node.call( this, options );

  if ( something ) {
    this.addChild( new SomethingNode() );
  }
}
```
since ```new ExampleNode( { left: 50 } )``` behaves very differently, only properly positioning the first example. The options (which may contain positional/bounds-related Node options) should generally only be called AFTER adding all children, which has to happen after the supertype call.

In the BilliardsTableControl example, would things be better if I broke the "options object" into two parameters to the constructor instead?

**Comment by pixelzoom** [comment]
@jonathanolson and I discussed via Skype.

**Comment by jonathanolson** [comment]
BilliardsTableControl relies on the supertype constructor creating leftPicker/rightPicker (which are then added as ancestors in a VBox), so I can't use the 'overriding children' pattern. Ignoring that file for now.

**Comment by jonathanolson** [comment]
I'm thinking of bailing on the other two (BilliardTableIcon and GradientIndicatorNode) since they directly extend Node and don't handle options themselves, thus it's a preference for:
```js
Node.call( this, {
  children: [ a, b, c ]
} );
this.mutate( options );
```
OR
```js
options = options || {}; // it's just being used for Node options, so no need to extend
assert && assert( !options.children, 'Unsupported option' );
options.children = [ a, b, c ];
Node.call( this, options );
```

and I find the first to be a bit cleaner.

Changes were applied in two of the cases. @pixelzoom can I get your opinion on whether this is sufficient?

**Comment by pixelzoom** [comment]
Re https://github.com/phetsims/proportion-playground/issues/91#issuecomment-300256095 ...  A subtype of Node either does or doesn't allow the client to decorate (add additional children to) the Node.  What you've identified as the "cleaner" pattern doesn't behave correctly in either case - the subtype can't be decorated, and the client can accidentally blow away the subtype's children. 

That said... Not super important in this case, since these are sim-specific types that are unlikely to see other use.   So I'm OK if you don't change them.

**Comment by pixelzoom** [comment]
FYI, here are the 2 patterns that I use related to decoration via `options`.

```js
options = _.extend( {...}, options );

// Pattern that supports decoration
options.children = [ child1, child2, child3 ].concat( options.children || [ ] );
Node.call( this, options );

// Pattern that does not support decoration
assert && assert( !options.children, 'decoration not supported' );
options.children = [ child1, child2, child3 ];
Node.call( this, options );
```

**Comment by jonathanolson** [comment]
> the client can accidentally blow away the subtype's children.

I generally only have a 'children' option on `Node`, layout types, or other basic Scenery types (e.g. `Path`), and generally never override this. If it's a problem, we should probably fix it first in common code.

I believe almost every button (`RectangularButtonView`, `RoundButtonView`), `CheckBox`, `Panel`, `HSlider` and many other types completely break if you pass `{ children: [] }` in their options. Should this be brought up at developer meeting if it's an issue?

> So I'm OK if you don't change them.

I slightly prefer the current code for this sim.

**Comment by pixelzoom** [comment]
Indeed, many (most?) common-code components will break if you attempt to decorate them.  This came up recently when @samreid needed to decorate `ProbeNode`, and he added decoration support (line 212).  

In general, I prefer to _not_ support decoration, as it tends to simplify implementation. And if I need to decorate a Node, I don't decorate it directly -- I add the decoration and the decoratee to a parent Node.

I'm totally OK with leaving things in this sim "as is".  So I'll close this issue.
