### ISSUE TITLE
options vs constructor parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#92]
Related to code review #69.

There are some cases where I think options (rather than constructor parameters) would improve readability at constructor call sites.

`BilliardsTable` is an example, others are similar.  Here's the current constructor signature:

```js
function BilliardsTable( initialLength, initialWidth, visibleProperty, controlsVisibleProperty )
```

Here are the current uses:

```js
// ExploreScreen
    var billiardsTable = new BilliardsTable( 6, 3, new Property( true ), new Property( true ), true );

// BilliardScene
    this.leftTable = new BilliardsTable( 5, 5, this.leftVisibleProperty, this.leftControlsVisibleProperty );
    this.rightTable = new BilliardsTable( 5, 5, this.rightVisibleProperty, this.rightControlsVisibleProperty );
```

Difficult to know what the arguments are without looking at the constructor documentation.  And also difficult to spot that the call in `ExploreScreen` contains an extra argument (there are 5 args, but 4 parameters.)  The call in `ExploreScreen` also requires providing some dummy Property instances.

Imo, this is a job for `options`, e.g.:

```js
function BilliardsTable( options ) {

  options = _.extend( {
    initialWidth: 5,
    initialHeight: 5,
    visibleProperty: new Property( true ),
    controlsVisibleProperty: new Property( true ) 
  }, options );

   ...
}
```

The uses become:

```js
// ExploreScreen
    var billiardsTable = new BilliardsTable( {
      initialWidth: 6,
      initialHeight: 3
    }  );

// BilliardsScene:
    this.leftTable = new BilliardsTable(  {
      visibleProperty: this.leftVisibleProperty, 
      controlsVisibleProperty: this.leftControlsVisibleProperty 
    } );
    this.rightTable = new BilliardsTable( {
      visibleProperty: this.rightVisibleProperty, 
      controlProperty: this.rightControlsVisibleProperty 
    } );
```

Unclear whether you want to change anything at this point.  Just mentioning that this did affect readability during the code review.

**Comment by jonathanolson** [comment]
Agreed, options usage there is more readable. I'll plan to refactor some sites (assigned to me for that).

@pixelzoom, any other areas besides BilliardsTable where you would recommend this?

**Comment by pixelzoom** [comment]
@jonathanolson asked:
>  any other areas besides BilliardsTable where you would recommend this?

I did a quick look, didn't see any others. Guess I zeroed right in on BilliardsTable ;)

**Comment by jonathanolson** [comment]
Done in commit above.
