### ISSUE TITLE
Screen constructors are confusing because of icon code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#93]
Related to code review #69.

`ExploreScreen` is confusing because there's a bunch of stuff related to creating the home screen icon that's in the constructor.  I was wondering "why does ExploreScreen need an additional BilliardsTable instance? And why doesn't PredictScreen have one?"

Recommended to move the code that creates icons (home screen and navbar) to private functions, outside of the constructor.  Ditto for `PredictScreen`.

**Comment by pixelzoom** [comment]
@jonathanolson I went ahead and did this because it was easy.  If you don't like it, feel free to revert or change.  If you like it, close.

**Comment by jonathanolson** [comment]
Agreed, looks more readable. Thanks!
