### ISSUE TITLE
provide an overview of memory management in implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/proportion-playground#96]
Related to code review #69 and https://github.com/phetsims/proportion-playground/issues/95.

implementation-notes.md should include a general overview of memory management.  What exists for the lifetime of the sim, what is created dynamically and therefore requires `dispose`, etc.

**Comment by jonathanolson** [comment]
Reviewed, and fixed one memory leak (commits above) discovered, since a DerivedProperty was getting created (but not disposed) for every PaintDripNode.
