### ISSUE TITLE
RadioButtonGroup (used for scene selection buttons) cursor issue

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/proportion-playground#97]
It seems that the mouse-over cursor for the "selected" button is the default cursor, NOT the hand as I'd expect.

Seems to affect not just this sim, but other usages of the component (just added it into area-model and noticed).

@ariel-phet, thoughts on whether this could be changed to STAY as the hand-cursor like would be expected?

**Comment by ariel-phet** [comment]
@jonathanolson - honestly I have never noticed this behavior (since normally I only hover over the scene I would like to switch to). It has never caused any user interaction issues in its current state, and I doubt it would be a problem if the hand appeared as you expect.

If you wish to adjust it moving forward for PP and area-model, feel free. No maintainence releases or such necessary however.

**Comment by jonathanolson** [comment]
I'd also like to verify that no-one is relying on this behavior, tagging for developer meeting.

**Comment by pixelzoom** [comment]
OK with me to change the behavior.  Current behavior doesn't bother me.

**Comment by samreid** [comment]
To me, having the arrow cursor over the selected radio button is a useful cue that you are already in that selection, and that pressing it would do nothing.  What is the reason for changing this?

@mkaoudis and @Denz1994 agree about that

@aadish says it should only be a hand cursor if pressing the button would do something.

**Comment by pixelzoom** [comment]
Here's the related code in RadioButtonGroup, line 260:

```js
    // make the unselected buttons pickable and have a pointer cursor
    property.link( function( value ) {
      if ( self.enabledProperty.get() ) {
        for ( i = 0; i < contentArray.length; i++ ) {
          if ( contentArray[ i ].value === value ) {
            buttons[ i ].pickable = false;
            buttons[ i ].cursor = null;
          }
          else {
            buttons[ i ].pickable = true;
            buttons[ i ].cursor = 'pointer';
          }
        }
      }
    } );
```

**Comment by samreid** [comment]
We decided the current behavior is desirable.
