### ISSUE TITLE
1 : 2 Switch images are not scaled equally

### ISSUE THREAD

**Issue by phet-thor** [phetsims/proportion-playground#98]
On both billiards screens (Explore and Predict), the size of the images for the one and two billiard tables are not the same size.

![image](https://cloud.githubusercontent.com/assets/28736100/26122831/1362ed5c-3a36-11e7-8522-2403317b5e83.png)

For comparison, the apples 1 : 2 switch is the same size.
![image](https://cloud.githubusercontent.com/assets/28736100/26123105/f6a96ea6-3a36-11e7-85d4-3623cdc339e9.png)

We should make the scaling of both of the images like that of the apples, same size across the slider.
Seen on: Windows 10 + Chrome
Related: https://github.com/phetsims/tasks/issues/839
URL: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-rc.1/proportion-playground_en.html
Version: 1.0.0-rc.1 2017-05-12 04:41:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Language: en-US
Window: 1920x950
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"7b0852e8","branch":"HEAD"},"babel":{"sha":"a47e061a","branch":"master"},"brand":{"sha":"c904b097","branch":"HEAD"},"chipper":{"sha":"9dde2e9c","branch":"HEAD"},"dot":{"sha":"6b4ec39c","branch":"HEAD"},"joist":{"sha":"84ba3f90","branch":"HEAD"},"kite":{"sha":"7d2df183","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"11406a81","branch":"HEAD"},"proportion-playground":{"sha":"1b1b89c4","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"a83739b9","branch":"HEAD"},"scenery-phet":{"sha":"9f07ef29","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"1c94ce39","branch":"HEAD"},"tandem":{"sha":"a336a3f3","branch":"HEAD"}}

**Comment by jonathanolson** [comment]
Fixed in master, @phet-steele or @phet-thor does that look good? (Keep open, I'll need to cherry-pick commit to RC branch).

**Comment by phet-thor** [comment]
fixed, thanks @jonathanolson

**Comment by jonathanolson** [comment]
Cherry-picked, thanks!
