### ISSUE TITLE
long string text looks too small to read in pattern box

### ISSUE THREAD

**Issue by maggiewiseman** [phetsims/proportion-playground#99]
Test device: Macbook Air

Operating System: OS X 10.12.4

Browser: Chrome Version 58.0.3029.81 (64-bit)

Problem description:
Using long strings query parameter, text appears too small to read on main explore screen as well as on billiard scene and apple scene. 

Steps to reproduce:
1. Open sim with stringTest=long query parameter.
2. Click on left option after simulation loads (the one that would be "explore")
3. Observe the white box where the text "pattern" would appear. 
4. Click on billiards option at the top, observe that width and height text is difficult to read.
5. Click apple option at the top, observe that labels for "Total Cost" and "Apples"  are difficult to read.

Severity:

Screenshots:
![12345678901234567890123456789012345678901234567890 screenshot 1](https://cloud.githubusercontent.com/assets/17385784/26206140/f5b65276-3bb1-11e7-99bd-e4ac572e9152.png)
![screen shot 2017-05-18 at 10 09 03 am](https://cloud.githubusercontent.com/assets/17385784/26206242/436d53f2-3bb2-11e7-9e53-f3848ca48fd5.png)

![12345678901234567890123456789012345678901234567890 screenshot 2](https://cloud.githubusercontent.com/assets/17385784/26211847/8595523e-3bc1-11e7-83e0-b5b06933561e.png)
![screen shot 2017-05-18 at 11 57 20 am](https://cloud.githubusercontent.com/assets/17385784/26211859/8f9dc09a-3bc1-11e7-9e30-03e92ced8b18.png)

![screen shot 2017-05-18 at 12 27 30 pm](https://cloud.githubusercontent.com/assets/17385784/26213010/68638718-3bc5-11e7-9058-ae55ef22a03d.png)

Related to: phetsims/tasks/issues/839

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.0-rc.1/proportion-playground_en.html?stringTest=long
Version: 1.0.0-rc.1 2017-05-12 04:41:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
Language: en-US
Window: 1157x584
Pixel Ratio: 1.100000023841858/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"HEAD"},"axon":{"sha":"7b0852e8","branch":"HEAD"},"babel":{"sha":"a47e061a","branch":"master"},"brand":{"sha":"c904b097","branch":"HEAD"},"chipper":{"sha":"9dde2e9c","branch":"HEAD"},"dot":{"sha":"6b4ec39c","branch":"HEAD"},"joist":{"sha":"84ba3f90","branch":"HEAD"},"kite":{"sha":"7d2df183","branch":"HEAD"},"phet-core":{"sha":"76ec0204","branch":"HEAD"},"phetcommon":{"sha":"11406a81","branch":"HEAD"},"proportion-playground":{"sha":"1b1b89c4","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"a83739b9","branch":"HEAD"},"scenery-phet":{"sha":"9f07ef29","branch":"HEAD"},"sherpa":{"sha":"0e326d54","branch":"HEAD"},"sun":{"sha":"1c94ce39","branch":"HEAD"},"tandem":{"sha":"a336a3f3","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@maggiewiseman all of this is okay. Remember that a sim only needs to pass a stringTest by not having a string overextend into or onto another sim element. The fact that strings get smaller as they get longer is a good thing since otherwise they would cover the whole screen. In reality, a translator would never put such a long string in a sim where they would become impossible to read.

**Comment by amanda-phet** [comment]
Thanks @phet-steele I was going to talk to you about this when I came in today! Thanks for clarifying for us.
